name: C/C++ CI

on: [push, pull_request]

env:
  PYTHONUTF8: 1

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install
        run: sudo apt-get install fuse libfuse-dev
      - name: vcpkg build
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-linux
          token: ${{ github.token }}
          github-binarycache: true
      - name: build-test
        run: python3 build.py --enable_unit_test --enable_integration_test --vcpkg_root=${{ github.workspace }}/vcpkg --build_root=./build
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/securefs
          name: securefs-linux-amd64

  build-mac:
    runs-on: macos-11
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: pip
        run: pip install xattr
      - name: install
        run: brew install macfuse
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-osx
          token: ${{ github.token }}
          cache-key: macos-11-x64
          github-binarycache: true
      - name: build
        run: python3 build.py --enable_unit_test --vcpkg_root=${{ github.workspace }}/vcpkg --triplet=x64-osx --build_root=./build
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/securefs
          name: securefs-macos-amd64

  build-mac-arm64:
    runs-on: macos-11
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: pip
        run: pip install xattr
      - name: install
        run: brew install macfuse
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: arm64-osx
          token: ${{ github.token }}
          cache-key: macos-11-arm64
          github-binarycache: true
      - name: build
        run: python3 build.py --vcpkg_root=${{ github.workspace }}/vcpkg --triplet=arm64-osx --build_root=./build --cmake_defines CMAKE_OSX_ARCHITECTURES=arm64
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/securefs
          name: securefs-macos-arm64

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install
        run: choco install winfsp
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-windows-static-md
          token: ${{ github.token }}
          cache-key: windows
          github-binarycache: true
      - name: build-test
        run: python3 build.py --enable_unit_test --enable_integration_test --vcpkg_root=${{ github.workspace }}/vcpkg --triplet=x64-windows-static-md --build_root=./build
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/Release/securefs.exe
          name: securefs-windows-amd64
